---
  - hosts: app
    gather_facts: true
    become: true
    
    tasks:
    
    - name: Clearing the path
      file:
        state: absent
        path: /home/ubuntu/provision
      
    - name: Cloning the Git-Hub repository
      shell:
        cmd: git clone https://github.com/SaCut/provision

    - name: Provisioning the app instance
      ansible.builtin.command: bash /home/ubuntu/provision/provision_app.sh
    
    - name: Installing npm
      apt:
        pkg: npm
        state: present
      
    - name: Downloading Nodejs-6.x
      get_url:
        url: https://deb.nodesource.com/setup_6.x
        dest: /home/ubuntu/nodejs6.sh
     
    - name: Preparing nodejs version
      shell: 
        cmd: bash /home/ubuntu/nodejs6.sh
    
    - name: Installing nodejs in "web" server
      shell:
        cmd: sudo apt-get install nodejs -y
    
    - name: Installing pm2
      shell:
        cmd: npm install -g pm2
       
    - name: Restarting service NginX
      service:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: Launching the app
      ansible.builtin.command: bash /home/ubuntu/provision/seed_and_start.sh
    


#    - name: update and upgrade
#      apt:
#        update_cache: yes
#        upgrade: dist
#        force_apt_get: yes
#        cache_calid_time: 3600

#    - name: install python-software-properties
#      apt:
#        pkg: python-software-properties
#        state: present
    
#    - name: Installing nodejs in "web" server
#      get_url:
#        url: https://deb.nodesource.com/setup_6.x
#        dest: /etc/nodejs6
        
#      apt:
#        pkg=nodejs
#        state=present
      
#    - name: Installing NPM
#      apt:
#        pkg: npm
#        state: build-dep
#        state: fixed
