# debguged_ec2 AWS playbook overriden default python 2.7 to python3
---

- hosts: localhost
  connection: local
  gather_facts: True
  become: True

  vars:
    key_name: DevOpsStudents
    region: eu-west-1
    image: ami-05ddd896984ff509a
    id: "Node-app"
    sec_group: "sg-081225d46b6a3f673"
    subnet_id: "subnet-09c2979c7e39bc368"

    # add the following line if ansible by default uses python 2.7
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Facts
    block:

    - name: Get instances facts
      ec2_instance_facts:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{ region }}"
      register: result

    - name: Provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"

    - name: Provision instance(s)
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        assign_public_ip: true
        key_name: "{{ key_name }}"
        id: "{{ id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ sec_group }}"
        image: "{{ image }}"
        instance_type: t2.micro
        region: "{{ region }}"
        wait: true
        count: 1
        instance_tags:
          Name: DevOps_Eng67_front-end

      tags: ['never', 'create_ec2']
